# Generated by Django 2.1.4 on 2019-11-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0002_auto_20191031_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'managed': True, 'ordering': ['created_at', 'name', 'status']},
        ),
    ]
