# Generated by Django 2.1.4 on 2019-11-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0003_auto_20191117_2303'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='current_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='last_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='max_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='min_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
